<?php
// $Id: custom_configurations.module,v 1  2012/05/9,  Marse Exp $  

/*
*Implementación de hook_views_pre_build
*/

function custom_configurations_views_pre_build(&$view) {
	$node = node_load(arg(1));
	
	if ($view->name == 'bloques_de_un_grupo' && $view->current_display == 'block_5') {  
   		$estilo = $node->field_shared_style['und']; 
		if($estilo[0]){
			$numero=$estilo[0][tid];
			foreach($estilo as $value) {
				$numero=$numero . '+' . $value['tid'];    
			}
    			$view->args['0'] = $numero;
    		}
  	}
 }


/**
* Implements hook_page_alter().
*/
function custom_configurations_page_alter(&$data) {
  if (isset($data['content']['system_main']['nodes'])) {
    $nids = element_children($data['content']['system_main']['nodes']);
    $nid = $nids[0];
    // We'll place the node comments inside a quicktabs block.
    $comments = $data['content']['system_main']['nodes'][$nid]['comments'];
    unset($data['content']['system_main']['nodes'][$nid]['comments']);
    $overrides = array('ajax' => 0, 'style' => 'Phylactere'); // Override some of the settings for the QT instance.
    $custom_tabs = array(
      array(
        'title' => 'MetalSpain',
        'contents' => $comments, // Custom tabs must have a contents property.
        'weight' => 0
      )
    );

    if(($data['content']['system_main']['nodes'][$nid]['body']['#bundle']!='page') && ($data['content']['system_main']['nodes'][$nid]['#bundle']!='page')){
     // Our 'node_activities' Quicktabs instance has just one tab, we're going to
    // add a second tab to it, containing the node comments.
    $data['content']['tabcomentarios'] = array(
      'content' => quicktabs_build_quicktabs('tabcomentarios', $overrides, $custom_tabs),
      '#weight' => 99,
    );}
  }

}
