<?php
// $Id: custom_configurations.module,v 1  2012/05/9,  Marse Exp $  

/*
*Implementación de hook_views_pre_build
*/

function custom_configurations_views_pre_build(&$view) {
	$node = node_load(arg(1));
	
	if ($view->name == 'bloques_de_un_grupo' && $view->current_display == 'block_5') {  
   		$estilo = $node->field_shared_style['und']; 
		if($estilo[0]){
			$numero=$estilo[0][tid];
			foreach($estilo as $value) {
				$numero=$numero . '+' . $value['tid'];    
			}
    			$view->args['0'] = $numero;
    		}
  	}
 }
